### ISSUE TITLE
1.8 update

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Graves#160]
- [x] weird catacombs generation
- [x] https://github.com/NightKosh/GraveStone-mod/pull/156
- [x] #163
- [x] #20
- [x] Check and fix code style and imports in all project after merging
- [x] Replace vanilla skeletons by my skeletons
- [x] Wither spawner doesn't work
- [x] Fix items rendering, #188 .
- [ ] Fix undertacker
- [x] #159

**Comment by NightKosh** [comment]
https://github.com/NightKosh/GraveStone-mod/pull/157

**Comment by NightKosh** [comment]
https://github.com/NightKosh/GraveStone-mod/pull/156

**Comment by NightKosh** [comment]
#163

**Comment by NightKosh** [comment]
#20

**Comment by Zone22** [comment]
I'm looking forward to the 1.8 release!
