### ISSUE TITLE
"Unnamed block, report to mod author"

### ISSUE THREAD

**Issue by 3mia** [NightKosh/Gravestone-mod-Graves#206]
Hello so I noticed broken texture item in my recipe list which is called "Unnamed block, report to mod author" and its ID is 1272. How do I remove that recipe or whatever it is? :)

**Comment by NightKosh** [comment]
Hm.  What is it? Can you show screenshot of this recipe?
Also, which version of the Minecraft and mod you used?

**Comment by 3mia** [comment]
http://imgur.com/IivBdxg
I'm using minecraft 1.7.10, 
Forge 10.13.4.1614,
Gravestone 2.16.1
That item itself has no recipe, it's just shown in crafting list, I prefer not to see that

**Comment by 3mia** [comment]
Also just noticed a bug with a "Sword of a fallen warrior", I placed it on ground and from one side it looked like floating, form otehr side I couldnt see that, like paper at side, and other side was ok like sword was put in ground directly, hm

**Comment by 3mia** [comment]
Let me know if you have any news :)

**Comment by NightKosh** [comment]
As for item - It looks like you use NEI or some another similar mod, which shows all items, even special "technical" items, which are mostly "hidden". So I suppose this is an "invisible block", which  I use as a wall for some special cases(to prevent some problems with memorials collisions). This block hasn't got a texture(it is transparent) this is why it looks weird as item.

**Comment by NightKosh** [comment]
As for swords gravestones - this is a known problem. https://github.com/NightKosh/Gravestone-mod-Graves/issues/92
