### ISSUE TITLE
FPS lag

### ISSUE THREAD

**Issue by SvEgiiVEteR** [NightKosh/Gravestone-mod-Graves#207]
хорошо что разработчик русский)

вообщем у меня возле катакомб сильно падает фпс.с 10 -20 модами от 15 до 20(фпс в среднем от 100 до 40)
с одним GraveStone-2.16.1.jar падает с 100-70 до 30 но чувствуются мелкие фризы.
на чистом майне с 1 модом 30 фпс это же не нормаль?
если нужно дам свою конфу ПК и так далее...
у товарища нвидео а у меня радеон...у него норм с фпс(и модов примерно 60+) у меня же..просто ужас.

**Comment by NightKosh** [comment]
Привет. Это обусловлено большим количеством мобов + могил. Я сейчас как раз таки занимаюсь оптимизацией могил, дабы хоть как-то улучшить производительность + планирую перенести подземную часть катакомб в отдельное измерение, что тоже улучшит ситуацию. Но, к сожалению с временем у меня сейчас беда - работа + экзамены + госы + диплом...

**Comment by SvEgiiVEteR** [comment]
про мобов я понимал, по этому улетал далеко потом обратно к катакомбам(так как при гене их там тьма сразу появляеться). но всё равно фпс низкий 10-20 и то редко.
так же пробовал срезать верхушку территории /nukeup этим модом LagFix-2.0.1-mc1.7.10-forge.jar
но тоже не помогало может пару фпс и всё(а там все могилки срезаються + я копал на куба 5 вниз и всё что выше уничтожалось, вход могилы забор)
тут ещё может железный конфликт быть с ATI скажем.потому что у товарища моего нвидео, компьютеры почти схожы.и проц и озу...
если что буду рад протестировать...удачи в делах))
ещё с помощью LagFix-2.0.1-mc1.7.10-forge.jar удалял тайлентилы ..это лучше помогало на фпс +10

**Comment by Bogdan-G** [comment]
проблема рендерера, а пенос в отд мир бредятина не много, ибо так оно лагать будет и в отд мире все по той же причине.

**Comment by NightKosh** [comment]
Ну, срезать поверхность не обязательно. Есть конфиг(не помню уже название) отключающий генерацию могил на поверхности, оставляя только сам вход. Кстати, можно снизить расстояние от могилы, необходимое для спавна, а так же увеличить время между спавном мобов - это должно снизить количество мобов(но при этом и упростить прохождение). Ну, в принципе и снизить количество комнат(не уверен, есть ли эта опция в последней версии или нет)

**Comment by NightKosh** [comment]
Что касаемо отдельного мира - тут не совсем всё так. Польза всё же будет - отделение наземной части катакомб от подземной + отсутствие каких-либо других мобов(помимо тех, что будут спауниться в катакомбах) и тайлов. Конечно это не даст значительных результатов, но всё же хоть чуть-чуть но улучшит ситуацию.

**Comment by NightKosh** [comment]
А ещё, в принципе, можно добавить отдельный конфиг, изменяющий рендеринг могил, на стандартные средства. Но тогда у них всех будет лишь один единственный "тип". Если, конечно, проблема именно с рендерингом(в чём я сомневаюсь, так как было бы крайне странно со стороны разработчиков майна, рендерить то, что не видно).

**Comment by SvEgiiVEteR** [comment]
@NightKosh в том то и дело не помогало срезания..эксперементы делал просто,выявлял из за чего фпс садиться..
"снизить количество мобов" ну это уже для процесса игры. а тут и убивания всех мобов не помогает.
"(в чём я сомневаюсь, так как было бы крайне странно со стороны разработчиков майна, рендерить то, что не видно)."тут уже надо тестить...  мне...раз у меня конкретная просадка фпс

**Comment by NightKosh** [comment]
@SvEgiiVEteR а есть ли разница между дневным и ночным временем?

**Comment by Bogdan-G** [comment]
@NightKosh "Если, конечно, проблема именно с рендерингом(в чём я сомневаюсь, так как было бы крайне странно со стороны разработчиков майна, рендерить то, что не видно)." - по данным WR большую часть времени поток клиента был занят рендерером могилок. А поток сервера почти все время спал.

**Comment by SvEgiiVEteR** [comment]
@NightKosh нет разници не замечал..удаление всех TE через LagFix помогало но лишь на 10 фпс прибавляло. при том что удалялось 2000 те.учитывая количество и прибавление фпс..дело в чём другом.я склоняюсь к конфликту с видеокартой АМД
вот после 5 минут создания карты
http://i.imgur.com/3MnM4fZ.png
потом фпс по лучше и стабилнее.
а вот возле катакомб
http://i.imgur.com/HFDa4r1.png
график от мода sampler-1.60.jar

**Comment by Bogdan-G** [comment]
а не может ли быть рекурсивный перерендеринг? т.е. отрендерило, выгрузило,снова рендерит и так рекурсия, вместо того чтобы держать в памяти.

**Comment by SvEgiiVEteR** [comment]
насчёт входа не уверен. я его весь разломал на плоской крате. а вот могилы со цветми скорее всего. я их на кладбище все уничтожил после того как фпс упало с 120 до 39 после генеарции. ,после поломки могил со цветами поднялось до 60-70

**Comment by NightKosh** [comment]
@Bogdan-G Обработка ТЕшек не конфигурируема, так что, как минимум приходится обновлять счётчики для каждой могилы(примерно 20 раз в секунду) + как вы уже сказали, примерно в среднем раз в 500 тиков просчёт всего прочего(положение игрока, попытка спавна моба и прочие) - но всё это дело было донельзя оптимизировано в последней версии(что, в итоге, у меня 30 фпс подняло до 60) + в 1.8 просчёт всего этого будет для всех могил(в комнате) разом, что тоже чуточку улучшит ситуацию. Но в целом, всё это особо смысла не имеет, с учётом того, что нету разницы между ночным и дневным временем.

Что касаемо самих моделей могил - они все заранее создаются(по 1 штуке каждая) и используются для всех могил, так что тут тоже проблем быть не должно, разве что, как подметил @SvEgiiVEteR , проблема вполне может быть с рендерингом цветов и мечей.. Как появится время попробую с этим что-нибудь сделать. Как минимум конфиг добавлю, отключающий их рендеринг вообще.

**Comment by Bogdan-G** [comment]
> донельзя оптимизировано в последней версии(что, в итоге, у меня 30 фпс подняло до 60)
бэкапорт изменения возможны?

**Comment by NightKosh** [comment]
@Bogdan-G Бэкпорт уже был.

**Comment by NightKosh** [comment]
Потестировал "цветочки". Выставил 1000 могил с цветами - 18фпс. Отключил рендеринг цветов - 60фпс. Пытался оптимизировать - бессмысленно - проблема именно в том, как майнкрафт рендерит предметы не в инвентаре. Соответственно с мечами аналогичная ситуация. Видимо придётся добавить конфиг для отключения цветов(либо как-нить впихнуть их в саму модель могил) + альтернативные модели для мечей(скорее всего те, что были раньше).

**Comment by Bogdan-G** [comment]
вот именно что рендер ваниллы убог

**Comment by NightKosh** [comment]
Поковырял ванильный код, повыкидывал часть ненужных действий. В итоге до 28 - 30 фпс поднялось. В принципе можно попробовать полностью перепилить ванильный рендер, может даже и заработает нормально)

**Comment by Bogdan-G** [comment]
свой рендер напрямую через LWJGL или OpenGL))

**Comment by NightKosh** [comment]
Свой рендер пожалуй уж слишком на столь не значительную задачу(проще просто отказаться от "мечей" и цветочков, либо же использовать свои модели). А вот разодрать ванильный и оставить только нужное - вполне вариант...

**Comment by Bogdan-G** [comment]
сделанные мною изменения в моем форке: https://github.com/Bogdan-G/Gravestone-mod-Graves/commit/fb5ae13bcebf57ef3f22a33b496d141ece6359c4 , у меня перед воротами +10фпс, и +5-10фпс перед жаровнями/входом в "домик". У SvEgiiVEteR все так же как было. 

Да эти изменения не совсем аналог того что сделано для 1.8+ ветки. Что еще можно предложить? Может какие то строки кода для амд карточек? Ибо нвидия+интел явно иначе сработала, чем амд+интел. Хотя может еще дело в AVX инструкции ЦП помимо вызовов в старое поколение (что тормозит так же фпс рост).

**Comment by NightKosh** [comment]
@Bogdan-G постараюсь на этих выходных смерджить, да остальные изменения с 1.8 перенести. Что ещё? честно говоря даже и не знаю, да и не уверен, что есть в этом смысл - не думаю, что получится получить сколь либо значимый прирост(а вот времени потратится не мало)

**Comment by Bogdan-G** [comment]
@NightKosh система рендера для 1.8+ чутка по другому чем 1.7.10, и я самопил в комменте пилил, может можно еще больше отвязать от вызовов в ванилу, по крайней мере у др модов таких то проблем нет, в теории ТЕ морозить/перевести в блок, а ивенты на могилку можно с записью координат сгенеренной могилки без непосредсвенного чека оной. Я имхо до конца не догоняю что такого тут чтобы фпс убегал.
PS гитхаб нотификации тупят - я чекаю каждый день, а только 24.02 пришло 2 уведомления 2дн и 4дн давности, т.е. часть приходит быстрее, часть похоже (если я точно заходил) реже (или мб кэш арбуза еще причина).

**Comment by Bogdan-G** [comment]
еще изменения в моем форке https://github.com/Bogdan-G/Gravestone-mod-Graves/commit/d4792e36400f31a5d15b653c185d55902185d461, на этот раз более эффективно, фпс у меня в плоском мире поднялся в 1.5-2раза, внутри тоже, я расковыривал ванильные вызовы, да как вариант согласен можно как с мечами своим кодом отрисовывать цветы.

**Comment by NightKosh** [comment]
@Bogdan-G наконец таки выдалось время заняться этим. Перенёс твои фиксы. Так же добавил к ним настройки, как в 1.8.9 для выбора способа рендеринга и отключения отрисовки цветов. Большое спасибо за помощь!

**Comment by NightKosh** [comment]
Ссылка https://minecraft.curseforge.com/projects/gravestone-mod-graves/files/2430785/download

**Comment by SvEgiiVEteR** [comment]
@NightKosh  мне фиксы на 1710 те не помогали если тока пару фпс.. щас это проверю))

**Comment by NightKosh** [comment]
@SvEgiiVEteR для отключения отрисовки цветов есть опция "renderGravesFlowers", а для упрощённых моделей могил из мечей "vanillaRendererForSwordsGraves"

**Comment by SvEgiiVEteR** [comment]
@NightKosh ну вообщем проверил стало лучше но не особо.
было где то от 20-до 24 фпсу входа.
щас от 31 до 40
и отключени рендеренга не помогло с приростом фпс )
и сейчас опять до 26 упало...
я думаю в целом на большенства машинах фпс думаю улучшится но лично мою проблему это ни как решило...
и в чём конкретно у меня проблема я даже не представляю...

**Comment by NightKosh** [comment]
@SvEgiiVEteR боюсь тут уже врятли что-то можно сколь-либо серьёзно изменить, разве что заменить все модели могилок на "обрезанный блок", но выглядеть это, конечно, будет убого. Если говорить про упрощение/оптимизацию логики спавна мобов - всё что можно было перенести с новых версий уже сделано(есть там конечно парочка доп фиксов не попавших в 1.7.10, но они требуют более заморочных, обширных измененей, и не смогут быть применены к уже существующим мирам), ну а дальнейшее упрощение только лишь в ущерб функциональности...

**Comment by SvEgiiVEteR** [comment]
@NightKosh я щас попробую sample сделать и кинуть файл,
но может ради теста и выяснить в чём дело сделать какую нибудь дебаг версию или скажем с отключением чего - либо.
так как игра нормально работает с 200 модами разными. а вот в этом месте даже с 2 или 3 модами  фпс прямо улетает в трубу.

**Comment by SvEgiiVEteR** [comment]
http://www.mediafire.com/view/2akmb92gmr6qph8

**Comment by Bogdan-G** [comment]
@NightKosh пожалуйста и спасибо вам :)
ПС странный перенос, 1/2 одного и 1/2 другого коммита :/

**Comment by NightKosh** [comment]
@Bogdan-G Странно, в уведомлении числится комментарий от вас, но здесь я его найти не могу... Касаемо его - я что-то забыл перенести? Вроде бы полностью перенёс весь контент файла рендерера из вашей ветки.

**Comment by Bogdan-G** [comment]
@NightKosh я затупил, перечитывал коммит и догнал, что все перенесли, поэтому комментарий с вопросом удалил.

**Comment by Bogdan-G** [comment]
еще изменения по теме фпс: https://github.com/Bogdan-G/Gravestone-mod-Graves/commit/242a9a9860e5af7eb3b06449e3957092a0ce75af

**Comment by NightKosh** [comment]
@Bogdan-G вот даже интересно, чем вам так switch-case не угодили?) Везде говорится что свитч таки чуть быстрей(хотя убедительных аргументов, всё же, найти не удалось), но с позиции читабельности, как по мне, он явно удобней. 
Для чего создавать свои собственные "адско-кирпичные блоки"?)
Корректировки в TickEventHandler стоят того? Что там вообще происходит?)
Касаемо баги с консольными командами - в 1,10 было пофикшено(без доп событий на остановку сервера)

У вас, случаем, нет желания заняться поддержкой 1.7 версии(любым удобным/приемлемым для вас способом)? Мне явно в ближайшее время не до этого будет - сейчас на 2 недели в командировку, да и после надо бы обнову к 1.11, 1.12 закончить, что, в целом, явно затянется ещё месяца на полтора, если не больше, а там ещё минус месяц на отпуск...

**Comment by Bogdan-G** [comment]
@NightKosh да не вопрос в какой то мере ее поддерживать.

**Comment by Bogdan-G** [comment]
пишите что именно нужно из изменений?

**Comment by NightKosh** [comment]
@Bogdan-G странно, очень странно, согласно документации должно быть наоборот, как раз таки сразу переходить к нужной ветке, без обхода всего остального.. ну да и ладно, раз уж тесты так показывают пусть так и будет).

**Comment by NightKosh** [comment]
@Bogdan-G что касаемо поддержки - у меня каких-либо конкретный требований нету, можете делать всё, что пожелаете. 
Честно говоря, мерджить столько изменений крайне лень, да и боюсь что-нить да поломается/потеряется по пути, и было бы, наверное, лучше если бы вы сами её и выкладывали(если вам такой вариант приемлем). Не уверен правда, можно ли расшарить доступ на curse-forge. 
При необходимости я не буду против ни отдельных страниц на форуме и прочих сервисах с отдельным описанием / ссылками на загрузку, если вам оно понадобится)

**Comment by Bogdan-G** [comment]
@NightKosh гм ок, еще вопрос: версия я так понял по сурсам этого репозитария + изменения поверх? Ибо есть еще мой форк-репо и может чем то отличаться или иметь изменения балансовые под мой модпак(явно не по теме может быть).
