### ISSUE TITLE
grave did not spawn in nether

### ISSUE THREAD

**Issue by kotoroshinoto** [NightKosh/Gravestone-mod-Graves#210]
was in nether fort, no grave at death site

**Comment by kotoroshinoto** [comment]
apologies, wrong mod

**Comment by kotoroshinoto** [comment]
Tried this mod instead of the one I had been using. 

Dying in nether caused a ticking entity nullpointer crash

**Comment by kotoroshinoto** [comment]
and when it doesn't crash, still no grave

**Comment by kotoroshinoto** [comment]
crashes happen in overworld as well

**Comment by NightKosh** [comment]
Can you show a crash log ?

**Comment by kotoroshinoto** [comment]
If I can find the time I will. I've already moved on to a grave mod that doesn't bug out in the nether so the server will remain stable.

It could have been a mod interaction, but that seemed unlikely.
