### ISSUE TITLE
Mod cross-compatibility issue: Gravestones in claimed chunks unbreakable by grave owners or ops.

### ISSUE THREAD

**Issue by Insidious611** [NightKosh/Gravestone-mod-Graves#212]
Hi, Moderator on the MMD server here. Gravestones in claimed chunks seem to be unbreakable by their owners (the people who died to create the gravestone), or by ops/Admin roles. I've also been unable to use /ftb chunks unclaim as an op/Admin rank to unclaim the chunk temporarily in order to break the gravestone.

**Comment by NightKosh** [comment]
So you are using 1.8 version of minecraft, are you? And "OnlyOwnerCanLootGrave" option set to "true". Am I right?

**Comment by Insidious611** [comment]
No on both counts.

**Comment by NightKosh** [comment]
Minecraft 1.10.2 ? I'm still not update my mod for this version of Minecraft.
