### ISSUE TITLE
placed Graves disappear

### ISSUE THREAD

**Issue by Streetdigger2** [NightKosh/Gravestone-mod-Graves#213]
Hi,

I'm playing the Modpack Regrowth with the Mod Gravestone v2.16.0 included. I craft some Gravestones, Crosses and Plates by myself to build a graveyard and they all disappeard after a few seconds. It doesn't matter wich Item nor Material I used. Is there any rule I have to follow (may be light level or something else)?

Kind regards
Streetdigger2

**Comment by NightKosh** [comment]
1) Try to get latest version (2.16.1)
2) If this problem will occurred again - post here your logs, it may contains some helpful information(or may not).
3) Another potential reason of such problem is "RemoveEmptyGraves" option. It used to remove empty graves on servers in some cases, and should be set to "false" by default. Check it please, may be it was changed by a mod pack creator.
