### ISSUE TITLE
спам в логе

### ISSUE THREAD

**Issue by SvEgiiVEteR** [NightKosh/Gravestone-mod-Graves#227]
наткнулся на такой спам при открытие мода в НЕИ
https://gist.github.com/ecf8ff17e28fe3aeba993f64987ef784
включаю выключаю мод в "подмножестве предметов" спам включается/выключается

**Comment by NightKosh** [comment]
А какая версия майна?

**Comment by SvEgiiVEteR** [comment]
1710. забыл упоминут

_Отправлено с моего Samsung GT-I9500 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
