### ISSUE TITLE
Выбор мира в исключениях

### ISSUE THREAD

**Issue by Star-Craft** [NightKosh/Gravestone-mod-Graves#228]
Сейчас в конфигах имеется возможность отключить генерацию могил в некотором диапазоне координат. но, как я понял, отключение происходит во всех мирах. добавить возможность выбора мира, для которого будет применён этот диапазон(т.е. дабы ограничение работало только в определённом мире).

P.S.: как же хорошо, что не нужно это переводить на англ. :D

**Comment by NightKosh** [comment]
А для какой версии майна нужно?

**Comment by Star-Craft** [comment]
1.7.10

**Comment by Bogdan-G** [comment]
не учитвает ид мира? ;D , а еще по коду кажется что запрещает при смерти игрока в этой области могилку создавать (но это не точно)

**Comment by NightKosh** [comment]
@Bogdan-G оно именно для этого и предназначено, кто-то просил, чтоб арены на серваках не нужно было очищать от могил. Странно даже, что сразу айди мира к этому не прикрутил.(@Star-Craft вы ведь говорите про измерения, а не полностью независимые миры?)

**Comment by NightKosh** [comment]
Поправил для 1.11.2. Чуть позже сделаю тоже самое и для остальных версий.
