### ISSUE TITLE
Multiple Graves spawn on death

### ISSUE THREAD

**Issue by Keaton1188** [NightKosh/Gravestone-mod-Graves#239]
Hey all, having an issue on our Horizons 3 server (noticed when we first opened it), whenever you die it creates two graves, one of the graves has nothing in, the other has your items in..

Minecraft version: 1.12.2

GaveStone Version; gravestone-1.10.0.jar

SpongeForge:
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-421703e
SpongeForge: 1.12.2-2503-7.0.0-BETA-2716

**Comment by NightKosh** [comment]
https://github.com/NightKosh/Gravestone-mod-Extended/issues/30

Minecraft version: 1.12.2

GaveStone Version; gravestone-1.10.0.jar

SpongeForge:
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-14f459d
SpongeForge: 1.12.2-2529-7.0.0-BETA-2730
Minecraft Forge: 14.23.0.2528

Another issue we are also having is; when players break their graves sometimes the items do not drop, nothing just comes out.

**Comment by Keaton1188** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24898745/32924277-be0c1394-cb33-11e7-9628-637a84129da9.gif)

Video of this happening, not sure if this is a mod issue or Sponge related.

**Comment by Keaton1188** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24898745/32924303-e28324ce-cb33-11e7-8df9-fd5199768f84.gif)

Video of this happening, not sure if this is a mod issue or Sponge related.

**Comment by NightKosh** [comment]
Oh. This is another gravestone mod. You should post this issue here https://minecraft.curseforge.com/projects/gravestone-mod

This is how my graves looks like:
![grave](https://media-elerium.cursecdn.com/avatars/99/770/636310332158664283.png)
