### ISSUE TITLE
Increase explosion resistance of graves

### ISSUE THREAD

**Issue by Sunconure11** [NightKosh/Gravestone-mod-Graves#241]
Even with things like mob griefing off, graves can easily be taken out by explosions. Would it be possible to add a config option to make them more explosion resistant?

**Comment by NightKosh** [comment]
It is already set to extremely high value. But It can't protect graves from destruction of ground under it.

**Comment by NightKosh** [comment]
If the reason of this probles is a result of ground destruction - try to set "OnlyOwnerCanLootGrave" to true - it should protect grave from destruction by any source except destruction by its owner
