### ISSUE TITLE
deadly tombstones

### ISSUE THREAD

**Issue by sonofthesnow** [NightKosh/Gravestone-mod-Graves#242]
"tombstone" которые появляются в деревнях(и не только) по какой то причине наносят урон, все бы ничего но иногда тупые жители просто убиваются о них, хорошо бы это как то исправить.

**Comment by sonofthesnow** [comment]
забыл уточнить, наносят урон если подойти к ним впритык

**Comment by NightKosh** [comment]
Странно, очень странно - ни разу не замечал подобного. На всякий случай всё же спрошу - вы случаем не перепутали мой мод с вот этим https://minecraft.curseforge.com/projects/gravestone-mod ?

**Comment by sonofthesnow** [comment]
до этого использовал этот, сейчас перешел на твой из-за Gravestone mod - Extended, вот скрины + еще пару визуальных багов.
https://fex.net/#!767508506155

**Comment by NightKosh** [comment]
Всё же речь не про могилы. Бага воспроизвелась - буду фиксить. 
Что касаемо проблем с локализацией - если вам не трудно, то переведите на свой язык.

**Comment by sonofthesnow** [comment]
да тупанул, не туда кинул. нужна УКР локализация? могу попробовать, до этого не занимался таким.

**Comment by NightKosh** [comment]
Лишней она точно не будет.)

**Comment by sonofthesnow** [comment]
ок. посмотрим что получиться

**Comment by sonofthesnow** [comment]
перевод https://fex.net/#!697161644021

**Comment by sonofthesnow** [comment]
тупанул с переводом одного слова, не нашел как и где оно используется, пока не наткнулся на него сегодня, исправил перезалил, ссылка та же
