### ISSUE TITLE
items loss

### ISSUE THREAD

**Issue by sonofthesnow** [NightKosh/Gravestone-mod-Graves#243]
было несколько случаев когда после смерти находя свое надгробия там не было моей брони, иногда всей иногда некоторых частей(может и другие вещи пропадают, просто пропажу брони я сразу заметил). провел пару тестов, в результате если у тебя полный под завязку инвентарь и все слоты одежды то после смерти некоторые случайные вещи исчезнут.
место в надгробие имеет лимит?

**Comment by NightKosh** [comment]
Нет, лимита нету.

**Comment by sonofthesnow** [comment]
первый раз я заметил это когда умер в одной броне, а когда пришел к надгробию вся одежда была просто на земле, в момент смерти других предметов кроме железного сета в инвентаре не было, второй раз после смерти мой железный сет исчез, ну и когда я тестил в креативе, исчез шлем железный

**Comment by sonofthesnow** [comment]
удалил все моды, оставил только Gravestone mod - Extended и Gravestone mod - Graves, вещи пропадают точно, заметил еще такую мелочь, при разбитии могилы щит выпал но не подобрался

**Comment by NightKosh** [comment]
Версия Майна 1.12 ?

**Comment by sonofthesnow** [comment]
1.12.2

**Comment by NightKosh** [comment]
Ну и последний вопрос, - настройки вы ведь не меняли, особенно "AmountOfSavedItems" ?

**Comment by sonofthesnow** [comment]
нет там 100 стоит(не обратил на него внимания когда первый раз читал конфиг), я  изменил только один пункт, это GenerateCemeteries=true

**Comment by NightKosh** [comment]
Пока что воспроизвести не удалось. Вещи стабильно теряются?
![1](https://user-images.githubusercontent.com/4181327/33559138-eb9f7eee-d91c-11e7-9c48-96c69566b04c.png)
![grave](https://user-images.githubusercontent.com/4181327/33559139-ebbce808-d91c-11e7-83d9-8b92cdb5f60c.png)

**Comment by sonofthesnow** [comment]
хм, протестил еще раз, в креативе с первой попытки получилось (я могилу лопатой не открывал) а вот сюрвайвл 3 раза тестил все нормально было(переходил с креатива в сюрвайвл)
![2017-12-04_23 04 42](https://user-images.githubusercontent.com/34198111/33576952-241af6a4-d94a-11e7-880c-4a8bbd5ff1e0.png)
![2017-12-04_23 06 16](https://user-images.githubusercontent.com/34198111/33576959-2a522056-d94a-11e7-9d29-dd6c3bdcfbdc.png)

**Comment by NightKosh** [comment]
А что это за мод на доп слоты? 
На всякий случай хотелось бы уточнить, знаете ли вы, что в креативе часть подбираемых вещей может теряться, если "главная панель" заполнена?

**Comment by sonofthesnow** [comment]
мод
https://minecraft.curseforge.com/projects/baubles?gameCategorySlug=mc-mods&projectID=227083

проблема у меня случилась первый раз в сюрвайвле

**Comment by sonofthesnow** [comment]
сегодня провел 10 всевозможных тестов, все вещи целы. сам начинаю сомневаться в наличии бага, но куда пропали вещи пока объяснить не могу, большая вероятность что я сам где-то, как-то тупанул, возможно стоит закрыть тему. надеюсь больше не случится.

**Comment by NightKosh** [comment]
Пусть пока повисит. Я ещё по тестирую, как будет время. Может и правда есть какой-нить хитрый баг - тогда главное понять как его воспроизводить.
Просто странно, что больше ни кто с таким не сталкивался(или же просто не репортил)

**Comment by NightKosh** [comment]
Ну как, возникала ли это проблема ещё раз?

**Comment by sonofthesnow** [comment]
не, все нормально, наверняка где-то сам накосячил
