### ISSUE TITLE
Crash on catacombs generation with BOP

### ISSUE THREAD

**Issue by Gamerbolts** [NightKosh/Gravestone-mod-Graves#246]
Hello I have a private modpack and I have been having crashes when users are going around the world if catacombs spawn. I noticed it looked like a conflict between gravestone & BOP. Here is the error log. https://pastebin.com/RWCjTnnh Any help is appreciated. Thank you :)

I am using MC 1.12.2 Forge 2555 and Mod version 1.0.12 and Gravestone Extended 1.2.3

Thank you for reporting!

For issues:
 * Be sure this is the same "graves" mod as you are using - sometimes I got bugs for another mods.(look at the graves pictures on my [site](http://gravestone.nightkosh.com/?page=about))
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here, or at least past it directly to the issue and embrace by "```".
 * If it is possible provide your logs.
 * Please provide your Minecraft version, Forge version and mod version.
 * Any additional information how to reproduce your problem and screenshots will be helpful.

**Comment by NightKosh** [comment]
Moved to https://github.com/NightKosh/Gravestone-mod-Extended/issues/54
