### ISSUE TITLE
Feature Request - OP can break graves

### ISSUE THREAD

**Issue by Gamerbolts** [NightKosh/Gravestone-mod-Graves#247]
Hi again, I was asked to see if there could be a config option where when you have the option set to be able to only break your own grave that OPs (admins) would still be able to break them. Is that possible?

**Comment by NightKosh** [comment]
So you'd like to allow graves looting/removing by any "creative" players too when "OnlyOwnerCanLootGrave" option set to "true"?

**Comment by Gamerbolts** [comment]
Yeah that would be good
