### ISSUE TITLE
[1.12.2] Fence connection [improvement]

### ISSUE THREAD

**Issue by JonasCiss** [NightKosh/Gravestone-mod-Graves#249]
I regconized that fences connect to gravestones. That looks a bit weird. Maybe this could be disabled to improve the look. 
![2017-12-13_17 50 05](https://user-images.githubusercontent.com/26455012/34072681-26bc6154-e28c-11e7-902f-4d19dc0af4f5.png)

**Comment by Geethebluesky** [comment]
This still happens with the latest version on 1.12.2, was it supposed to be fixed or labeled as "won't fix"?
