### ISSUE TITLE
huge fps lag because of too many mobs spawning.

### ISSUE THREAD

**Issue by mattrix444** [NightKosh/Gravestone-mod-Graves#251]
Hi i'm getting huge fps lag from the sheer amount of mobs spawning in the water (divers, drowned etc) its making the game unplayable. im using the latest version of the extended mod. GraveStone-Extended-1.3.0a3. theres literally like 100+ mobs spawning at once

**Comment by NightKosh** [comment]
@mattrix444 i've moved it here https://github.com/NightKosh/Gravestone-mod-Extended/issues/106

**Comment by mattrix444** [comment]
oh my bad. really sorry. thanks for the quick reply :)
