### ISSUE TITLE
Crashing after getting close to death location

### ISSUE THREAD

**Issue by redmars27** [NightKosh/Gravestone-mod-Graves#254]
Everytime someone gets closer to the location of the graves, the client crash, you have the crash log here: [https://gist.github.com/redmars27/55a9e2729e64a41f513d5a8acff3a7e4](https://gist.github.com/redmars27/55a9e2729e64a41f513d5a8acff3a7e4)

Two characters died quite close to each other, in a village house by zombies. After the crash if you login again, as you are already close to the location with the problem, it startup but after a couple of seconds it crash again. Let me know if you need more information. 

	| State  | ID                | Version      | Source                               | Signature                                |
	|:------ |:----------------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| UCHIJA | minecraft         | 1.12.2       | minecraft.jar                        | None                                     |
	| UCHIJA | mcp               | 9.42         | minecraft.jar                        | None                                     |
	| UCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.2.2611.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge             | 14.23.2.2611 | forge-1.12.2-14.23.2.2611.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | mercurius_updater | 1.0          | MercuriusUpdater-1.12.2.jar          | None                                     |
	| UCHIJA | gravestone        | 1.0.13       | GraveStone-1.12-Graves-1.0.13.zip    | None                                     |
	| UCHIJA | waila             | 1.8.23       | Hwyla-1.8.23-B38_1.12.jar            | None                                     |
	| UCHIJA | wawla             | 2.5.251      | Wawla-1.12.2-2.5.251.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | xaerominimap      | 1.14.9       | Xaeros_Minimap_1.14.9_Forge_1.12.jar | None                                     |
	| UCHIJA | xaeroworldmap     | 1.2.4        | XaerosWorldMap_1.2.4_Forge_1.12.jar  | None                                     |

Thanks,
Rredmars

**Comment by NightKosh** [comment]
Hello. Unfortunately I can't reproduce this but. Furthermore it looks incredibly weird, like you are using some kind of modified minecraft version.

As a temporal solution you can try to set "VanillaRendererForSwordsGraves" option to "false". It should help you.

**Comment by NightKosh** [comment]
Also try latest version https://minecraft.curseforge.com/projects/gravestone-mod-graves/files/2540033

**Comment by redmars27** [comment]
Thanks a lot, With the latest version works fantastic.

By the way, why do you say it is a modified minecraft version? The only "special" thing I am doing is to have the server part installed through a container with docker [https://hub.docker.com/r/itzg/minecraft-server/](https://hub.docker.com/r/itzg/minecraft-server/) Is this what do you see as weird? or is it something else?

**Comment by NightKosh** [comment]
As said in your crash log the reason of this problem in different "access modifier" for important field which used by mod - it should be available for any class for usage, but in your case it is not.

**Comment by NightKosh** [comment]
After your question I inspected my code again and understand that I was a little bit wrong - this method has "private" "access modifier". It was changed by me manually to "public" by Forge "access transformers". This mechanism should automatically change it at mod loading. 
For some reasons it doesn't works in your case.
