### ISSUE TITLE
1.7.10 Compatibility Req w Helpful Villagers

### ISSUE THREAD

**Issue by technodiva77** [NightKosh/Gravestone-mod-Graves#262]
Requesting mod compatibility with Helpful Villagers. I'm not a modder but i'm guessing it has something to do with HV wanting to convert all villagers to its mod and it conflicting with the undertaker. 
[2018-04-26-7.log.gz](https://github.com/NightKosh/Gravestone-mod-Graves/files/1951977/2018-04-26-7.log.gz)

**Comment by NightKosh** [comment]
Sorry, but I do not support 1.7.10 version of minecraft anymore.
