### ISSUE TITLE
No texture for zombie/skeleton horses.

### ISSUE THREAD

**Issue by Sketaful** [NightKosh/Gravestone-mod-Graves#267]
Having som problems with this mod (which I love othervise). 
First. The skin for the horses (zombie/skeleton) isn't working. All I get is a big white box. Looks kinda fun seeing zombies and more ride around on a white box but a horse would look better.
Ex: https://imgur.com/a/FvDDcDm

Secondly. I cant use the chisel on a grave. I get the window showing me I can write but it just blinks past and closes down. WAILA shows ERROR as well when looking at a grave (screen).
Ex. https://imgur.com/a/tN3YDrZ

Third. Why does it show like it's two tabs sharing space in the creative inventory? 
Never did before this mod.
(Like this: https://imgur.com/a/cPtQWzn)

Also found these errors in the log:
https://gist.github.com/Sketaful/81cfceb6e57c992dfbd0ce8bbcf589f3

**Comment by NightKosh** [comment]
Hello. Thank you for report. It looks like you use one of the "release" version for 1.12.2, aren't you?
All this issues are know and furthermore they are already fixed in latest beta version of mod:

https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2568060
