### ISSUE TITLE
Mobs spawning on Mooshroom Island

### ISSUE THREAD

**Issue by scribbler957** [NightKosh/Gravestone-mod-Graves#271]
MC 1.12.2, Gravestone 1.0.16
I'm setting up on a mooshroom island and I've seen vampire bats and phantom armor spawning. I've only seen the armor near the shore, but the bats I've seen inland. There are no other biomes on or near this landmass (except ocean).

**Comment by NightKosh** [comment]
Moved to https://github.com/NightKosh/Gravestone-mod-Extended/issues/146
