### ISSUE TITLE
Feature request: please add option to blacklist graves in certain dimensions so as to make better mod interoperability!

### ISSUE THREAD

**Issue by alxpettit** [NightKosh/Gravestone-mod-Graves#272]
Forge version: 14.23.4.2705.
Minecraft version: 1.12.2
Relevant installed mods:
GraveStone-1.12.2-Graves-1.0.16.jar
GraveStone-1.12.2-Extended-1.3.0b7.jar
DimensionalDoors-3.0.9-287.jar

Players on my server have problems with returning from limbo (in which case, all the stuff in inventory is supposed to stick when they fall into the void, then resurrect), but instead gravestone takes the items and... um... immediately throws them away. :(

`2018/07/04 13:01:51 [INFO] Can not create [redacted]'s grave at 528x-180x18`

Please add some way of blacklisting this mod's gravestone functionality in the limbo dimension so that DimensionalDoors is still playable! Thanks :)

**Comment by alxpettit** [comment]
If you don't have much time to do this, do you accept pull requests? I'd be happy to help!

**Comment by NightKosh** [comment]
Sorry for waiting. I was at vacation for some time. I'm planned to start working on it on holidays(tomorrow). But if you'd like to help I'll be glad to accept your pull requests.
P.S. I already has a method for similar purposes in "extended" mod, so it just should be moved to "graves" mod. ( https://github.com/NightKosh/Gravestone-mod-Extended/blob/master/src/main/java/nightkosh/gravestone_extended/config/ConfigsHelper.java )

**Comment by NightKosh** [comment]
Hello. Sorry for releasing new version of mod so long. Here is a new version https://minecraft.curseforge.com/projects/gravestone-mod-graves/files/2596352 
The option you are needed is "PlayerGravesDimensionalBlackList"

Are your question about API actual?

**Comment by alxpettit** [comment]
Hi! Do you mean the issue I opened where I had trouble compiling your code? Those questions still apply, yes! I'd like to know how to compile it so that I can test my pull requests if I have things to contribute. ^.^
