### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by Sunconure11** [NightKosh/Gravestone-mod-Graves#275]
https://pastebin.com/jcJzMEP8

**Comment by drakray** [comment]
I got that too https://pastebin.com/z2ueebrM
MC 1.12.2
Forge 2747
Grave 1.0.17
Extended 1.3.0b7

**Comment by QueenBonnydust** [comment]
Also got this problem, same versions as post directly above.

**Comment by NightKosh** [comment]
https://minecraft.curseforge.com/projects/gravestone-mod-graves/files/2598353
