### ISSUE TITLE
Crash between this mod and betas of F&A

### ISSUE THREAD

**Issue by Sunconure11** [NightKosh/Gravestone-mod-Graves#277]
https://paste.dimdev.org/ajosicalis.mccrash

**Comment by Sunconure11** [comment]
It's not related to the version of Forge, it's related to villagers.

https://pastebin.com/KFpZzA7V

As the newest dev of F&A, I am allowed to beta-test F&A, and as a result, stumbled upon this.

https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival

**Comment by Sunconure11** [comment]
https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/806

**Comment by NightKosh** [comment]
https://github.com/NightKosh/Gravestone-mod-Extended/issues/153
