### ISSUE TITLE
Add Config To Disable Grave Drop (Request)

### ISSUE THREAD

**Issue by KenyMylankca** [NightKosh/Gravestone-mod-Graves#285]
Can you add a simple config to disable the grave drop (itself) please? I just need only the items in it, not the grave. Thanks.

**Comment by NightKosh** [comment]
Added. It is called "DropGraveBlockAtDestruction" .
I'll post link on new version when it will be released.

**Comment by KenyMylankca** [comment]
thank you so much

**Comment by NightKosh** [comment]
https://minecraft.curseforge.com/projects/gravestone-mod-graves/files/2629433
