### ISSUE TITLE
Significantly reduce the frame rate

### ISSUE THREAD

**Issue by MinecraftXy** [NightKosh/Gravestone-mod-Graves#305]
The head on the tombstone often becomes translucent, and the chest near the incident also becomes translucent. When I see the tombstone the frame rate drops so badly and renders a lot of terrain, I can even look for the tombstone through stuttering. Minecraft version: 1.8.9+optfine
That can break GC too
Only tombstones generated after the player's death
![2022-08-29 16 35 13](https://user-images.githubusercontent.com/105211292/187168668-75f4a055-cd5d-4d97-a232-cff79efb17bd.png)

**Comment by Subkolw23** [comment]
Can confirm. Came here to look for this.
Using this mod on 1.12.1 and the gravestone tends to cause a lot of lag.
Even looking into the direction the gravestone is placed causes the frames to drop
