### ISSUE TITLE
villagers id

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Graves#86]
Get correct villagers id for villagers from another mods insead of using static values.
- [x] Forestry beekeper
- [x] Forestry lumberjack
- [ ] Growthcraft brewer
- [ ] Thaumcraft (Thaumaturge)

Add support for next mods
- [ ] Thaumcraft (Moneychanger)
- [ ] Railcraft
- [ ] Tinker construct
- [ ] Village Taverns

**Comment by da3dsoul** [comment]
Primitive Mobs has villagers too, and they don't work right of course. They don't have an API of sorts atm. I PMed the dev about it.

**Comment by NightKosh** [comment]
Add profession name for new thaumcraft villager

**Comment by katzenpapst** [comment]
https://sites.google.com/site/witcherymod/

Witchery adds the "Apothecary" villager and Town Guards. Not sure if the latter even count as villagers, though.

**Comment by NightKosh** [comment]
Moved to https://github.com/NightKosh/Gravestone-mod-Extended/issues/8
